project:
  type: website
  output-dir: docs

execute: 
  freeze: auto

website:
  open-graph: true
  title: "Notes to Myself"
  navbar:
    background: "blue"
    left: 
      - "by Stephen Parton"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/spinbris
      - icon: twitter
        href: https://twitter.com/spinb
      - icon: linkedin
        href: https://www.linkedin.com/in/stephen-parton-2737594/
date-format: "DD-MM-YYYY"
format:
  html:
    theme: 
      light: litera
      dark: darkly
    css: styles.css
    highlight-style: espresso

editor: visual

